server:
  port: 8083
  servlet:
    context-path : /prod/api/${spring.application.name}

spring:
  application:
    name: postify
  datasource:
    url: jdbc:mysql://localhost:3306/postify
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect